const data = [
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "something",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    deposit: 4000,
    countInStock: 1,
    description: "car",
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Flexusenthusiast.com%2Flexus%2Flfa%2F&psig=AOvVaw3GI2WXlRZ91IwSQMECOVPn&ust=1670580008402000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCPjq0dXh6fsCFQAAAAAdAAAAABAJ",
    transmission: "Automatic",
    maxSpeed: 325,
    power: "520 hp",
    price: 1500,
    deposit: 2000,
    countInStock: 1,
    description: "2 door, orange car",
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    deposit: 2000,
    countInStock: 1,
    description: "car",
    deposit: 4000,
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    deposit: 2000,
    countInStock: 1,
    description: "car",
  },
];

module.exports = data;
