const data = [
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    countInStock: 1,
    description: "car",
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    countInStock: 1,
    description: "car",
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    countInStock: 1,
    description: "car",
    deposit: 4000,
  },
  {
    brand: "Buggatti",
    make: "Bugatti Divo",
    image: "./images/Bugatti Divo.jpeg",
    transmission: "Automatic",
    maxSpeed: 380,
    power: "1,479 hp",
    price: 3000,
    countInStock: 1,
    description: "car",
  },
];

module.exports = data;
